
drop table if exists customer;

create table customer(

drop table if exists customer;

create table customer(
Customer_id int primary key,
Age	int not null,
Gender  varchar(10),
Item_Purchased varchar(100),
Category varchar(100),
Purchase_Amount int,
Location varchar(200),
Size	varchar(10),
Color varchar(50),
Season varchar(20),
Review_Rating DECIMAL(2,1),
Subscription_Status  varchar(20),
Shipping_Type	varchar(30),
Discount_Applied	varchar(10),
Promo_Code varchar(20), 
Previous_Purchases int,
Payment_Method	varchar(40),
Frequency_Purchases varchar(50)
)

select *from customer;

select count(*) from customer;


select avg(Review_Rating)  as avg_review_rating from customer;
select avg(Purchase_Amount) as avg_purfrom customer;
_______

-- Q1. What is the total revenue generated by male vs. female customers?
select Gender,sum(Purchase_Amount) as revune
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select Customer_id,Purchase_Amount
from customer
where Discount_Applied ='Yes' and Purchase_Amount >=(select avg(Purchase_Amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

select Item_Purchased ,round(avg(Review_rating),2)as Average_product_rating
from customer
group by Item_Purchased
order by Average_product_rating
desc limit 5;



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select Shipping_Type, round(avg(Purchase_Amount),2)as  avg_purchase 
from customer
where Shipping_Type in('Standard','Express')
group by Shipping_Type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non-subscriber.

select Subscription_Status,
count(Customer_Id)as total_customer,
round(avg(Purchase_Amount),2) as average_spend,
round(sum(Purchase_Amount),2) as total_revenue
from customer
group by Subscription_Status
order by total_revenue , average_spend;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select Item_Purchased,
round(100 * sum(case when Discount_Applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by Item_Purchased
order by discount_rate
desc limit 5;


-- Q7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

select Subscription_Status,
count(Customer_Id) as repeat_buyers
from  customer
where Previous_Purchases >5
group by Subscription_Status;


-- Q8. What is the revenue contribution of each age group? 

select Age_Group,
sum(Purchase_Amount) as total_revenue
from customer
group by Age_Group
order by total_revenue;
